package safeseattle.model;

import java.sql.Timestamp;

public class Comments{
	protected int commentId; //auto-incremented
	protected Users user;
	protected Posts post;
	protected String content;
	protected Timestamp created;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the commentId.
	public Comments(int commentId, Users user, Posts post, String content, Timestamp created) {
		this.commentId = commentId;
		this.user = user;
		this.post = post;
		this.content = content;
		this.created = created;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the commentId,
	// such as a foreign key reference to commentId.
	// Given commentId, we can fetch the full Post record.
	public Comments(int commentId) {
		this.commentId = commentId;
	}
	
	
	
	// This constructor can be used for creating new records, where the commentId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Comments(Users user, Posts post, String content, Timestamp created) {
		this.user = user;
		this.post = post;
		this.content = content;
		this.created = created;
	}

	public int getCommentId() {
		return commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}
	

	public Posts getPost() {
		return post;
	}

	public void setPost(Posts post) {
		this.post = post;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Timestamp getCreated() {
		return created;
	}

	public void setCreated(Timestamp created) {
		this.created = created;
	}
	
	
	
	
}